In [1]:
from prac_ingestion import getCrimeData

# Target forces
targetForces = ["metropolitan", "thames", "surrey", "sussex"]

masterDf = getCrimeData(
    forces=targetForces,
    basePath=r"C:\Users\noahe\Documents\Rockborne\Advance\2025crime",
)

# Inspect the result
masterDf.head()

Successfully loaded 1303098 records across 24 files.

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,4af53e255f9f3e69d1a295a288fe02488234842b18020e...,2025-01,Metropolitan Police Service,Metropolitan Police Service,-0.549537,50.815808,On or near Peel Close,E01031427,Arun 004A,Violence and sexual offences,Status update unavailable,NaN
1,af818ffc133013b72feaea4adead5a76c76aee204b98d4...,2025-01,Metropolitan Police Service,Metropolitan Police Service,0.884518,51.128775,On or near East Stour Way,E01032817,Ashford 009G,Other theft,Status update unavailable,NaN
2,NaN,2025-01,Metropolitan Police Service,Metropolitan Police Service,0.142112,51.589389,On or near A1112,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
3,NaN,2025-01,Metropolitan Police Service,Metropolitan Police Service,0.140194,51.582356,On or near Hatch Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
4,NaN,2025-01,Metropolitan Police Service,Metropolitan Police Service,0.140194,51.582356,On or near Hatch Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN

In [2]:
from prac_ingestion import cleaningValidation

cleanedDf = cleaningValidation(masterDf)

cleanedDf.head()

There are 1303098 values in the dataset before any processing at all
There are 115345 duplicate rows.
There are 1303098 values in the dataset after removing duplicates

List of null values in every column before handling null values
 Crime ID                  148056
Month                          0
Reported by                    0
Falls within                   0
Longitude                   5562
Latitude                    5562
Location                       0
LSOA code                   5562
LSOA name                   5562
Crime type                     0
Last outcome category     148056
Context                  1187753
dtype: int64


List of null values in every column
 Crime ID                 0
Month                    0
Reported by              0
Falls within             0
Longitude                0
Latitude                 0
Location                 0
LSOA code                0
LSOA name                0
Crime type               0
Last outcome category    0
dtype: int64

,Crime ID,Month,Reported by,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category
0,4af53e255f9f3e69d1a295a288fe02488234842b18020e...,2025-01,Metropolitan Police Service,-0.549537,50.815808,On or near Peel Close,E01031427,Arun 004A,Violence and sexual offences,Status update unavailable
1,af818ffc133013b72feaea4adead5a76c76aee204b98d4...,2025-01,Metropolitan Police Service,0.884518,51.128775,On or near East Stour Way,E01032817,Ashford 009G,Other theft,Status update unavailable
2,No Crime ID,2025-01,Metropolitan Police Service,0.142112,51.589389,On or near A1112,E01000027,Barking and Dagenham 001A,Anti-social behaviour,Unknown outcome category
3,No Crime ID,2025-01,Metropolitan Police Service,0.140194,51.582356,On or near Hatch Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,Unknown outcome category
6,No Crime ID,2025-01,Metropolitan Police Service,0.138830,51.583433,On or near Thatches Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,Unknown outcome category

In [4]:
from feature_engineering_transformation import yearConversion, textStandard
yearConvertedDf = yearConversion(cleanedDf)
yearConvertedDf.head()
textStandardDf = textStandard(yearConvertedDf)

textStandardDf.head()

Crime ID
Month
Longitude
Latitude
Location
LSOA code
LSOA name
Crime type
Last outcome category
Year
Force

,Crime ID,Month,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Year,Force
0,4af53e255f9f3e69d1a295a288fe02488234842b18020e...,2025-01,-0.549537,50.815808,On or near Peel Close,E01031427,Arun 004A,Violence and sexual offences,Status update unavailable,2025,Metropolitan
1,af818ffc133013b72feaea4adead5a76c76aee204b98d4...,2025-01,0.884518,51.128775,On or near East Stour Way,E01032817,Ashford 009G,Other theft,Status update unavailable,2025,Metropolitan
2,No Crime ID,2025-01,0.142112,51.589389,On or near A1112,E01000027,Barking and Dagenham 001A,Anti-social behaviour,Unknown outcome category,2025,Metropolitan
3,No Crime ID,2025-01,0.140194,51.582356,On or near Hatch Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,Unknown outcome category,2025,Metropolitan
6,No Crime ID,2025-01,0.138830,51.583433,On or near Thatches Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,Unknown outcome category,2025,Metropolitan